"""
BacklinkJobAssembler Module

Assembles complete BacklinkJobPackage from all components.
"""

import uuid
from datetime import datetime
from typing import Dict, Any

from .base import BaseModule


class BacklinkJobAssembler(BaseModule):
    """
    Assembles BacklinkJobPackage.

    Input:
        - input_minimal
        - target_profile
        - publisher_profile
        - anchor_profile
        - serp_research_extension
        - intent_extension

    Output:
        - BacklinkJobPackage: Complete JSON payload
    """

    def run(
        self,
        input_minimal: Dict[str, Any],
        target_profile: Dict[str, Any],
        publisher_profile: Dict[str, Any],
        anchor_profile: Dict[str, Any],
        serp_research_extension: Dict[str, Any],
        intent_extension: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Assemble BacklinkJobPackage

        Returns:
            Complete BacklinkJobPackage dict
        """
        self.log_step("Assembling BacklinkJobPackage")

        # Generate job_meta
        job_meta = {
            "job_id": str(uuid.uuid4()),
            "created_at": datetime.utcnow().isoformat() + "Z",
            "spec_version": "Next-A1-SERP-First-v1",
            "notes": "Auto-generated by BacklinkContent Engine"
        }

        # Determine generation_constraints
        language = target_profile.get('detected_language') or publisher_profile.get('detected_language', 'sv')

        generation_constraints = {
            "language": language,
            "min_word_count": self.config.get('min_word_count', 900),
            "max_anchor_usages": self.config.get('max_anchor_usages', 2),
            "anchor_policy": "Ingen anchor i H1/H2, placera i första relevanta stycke i mittsektionen.",
            "tone_override": None  # Use publisher_profile.tone_class
        }

        # Assemble package
        package = {
            "job_meta": job_meta,
            "input_minimal": input_minimal,
            "publisher_profile": publisher_profile,
            "target_profile": target_profile,
            "anchor_profile": anchor_profile,
            "serp_research_extension": serp_research_extension,
            "intent_extension": intent_extension,
            "generation_constraints": generation_constraints
        }

        # Validate
        self._validate_package(package)

        self.log_step(f"BacklinkJobPackage assembled: job_id={job_meta['job_id']}")

        return package

    def _validate_package(self, package: Dict[str, Any]) -> None:
        """Validate package has all required fields"""
        required_top_level = [
            'job_meta', 'input_minimal', 'publisher_profile', 'target_profile',
            'anchor_profile', 'serp_research_extension', 'intent_extension',
            'generation_constraints'
        ]

        self.validate_input(package, required_top_level)

        # Check intent_extension.overall is not null
        overall = package['intent_extension']['intent_alignment'].get('overall')
        if not overall:
            raise ValueError("intent_extension.intent_alignment.overall cannot be null")

        self.log_step("Package validation passed")
